# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: glados-checkin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  0 10,16 * * * 
      # 
      # https://tool.lu/crontab/ 
  #watch:
  #    types: started   

jobs:
  checkin:
    runs-on: ubuntu-latest
    #if: github.event.repository.owner.id == github.event.sender.id
    # https://p3terx.com/archives/github-actions-manual-trigger.html
    
    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
       # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
    - name: CheckInEDU
      run: |
        python3 CheckInEDU.py 
      env: 
        COOKIE: ${{ secrets.COOKEDU }}
